Fix --followings-output path
arc298/instagram-scraper pull request #718
Opened 2021-08-21 05:47 UTC by Roffild

Fix absolute and relative paths for --followings-output

2022-01-25 20:21 UTC, AlexNik requested changes

2022-01-25 20:21 UTC, AlexNik commented on instagram_scraper/app.py
> -            with open(scraper.destination+scraper.followings_output, 'w') as file:
open(os.path.join(scraper.destination, scraper.followings_output), 'w')

2022-02-12 15:30 UTC, Roffild commented on instagram_scraper/app.py
> -            with open(scraper.destination+scraper.followings_output, 'w') as file:
But it breaks the absolute path...

2022-02-12 15:56 UTC, AlexNik commented on instagram_scraper/app.py
> -            with open(scraper.destination+scraper.followings_output, 'w') as file:
Why?

2022-02-12 16:36 UTC, Roffild commented on instagram_scraper/app.py
> -            with open(scraper.destination+scraper.followings_output, 'w') as file:
```python
os.path.join(r"C:\download", r"D:\abs\path") == r"D:\abs\path"
```
Well... OK...

2022-02-14 19:58 UTC, AlexNik approved these changes

2022-02-14 19:58 UTC, merged