Fixing the weird API response causing graphql errors
arc298/instagram-scraper pull request #742
Opened 2021-11-16 17:44 UTC by novitae

2021-11-16 21:01 UTC, AlexNik requested changes

2021-11-16 21:01 UTC, AlexNik commented on instagram_scraper/app.py
> +                        node['urls'] = [pt1[e]['image_versions2']['candidates'][0]['url'] for e in range(len(pt1))]
`node['urls'] = [carousel_media['image_versions2']['candidates'][0]['url'] for carousel_media in details['carousel_media'])]`

2021-11-16 21:01 UTC, AlexNik commented on instagram_scraper/app.py
> +                        node['urls'] = [pt1[e]['image_versions2']['candidates'][0]['url'] for e in range(len(pt1))]
Why 0? Is it the highest resolution by default?

2021-11-17 08:18 UTC, novitae commented on instagram_scraper/app.py
> +                        node['urls'] = [pt1[e]['image_versions2']['candidates'][0]['url'] for e in range(len(pt1))]
idk why but the link of the medias is contained in a list containing only one element, theses links (for different sizes of pics)

2021-11-17 15:33 UTC, AlexNik commented on instagram_scraper/app.py
> +                        node['urls'] = [pt1[e]['image_versions2']['candidates'][0]['url'] for e in range(len(pt1))]
@novitae Could you fix the code review and i'll merge it.

2021-11-23 18:25 UTC, AlexNik commented on instagram_scraper/app.py
> +                        node['urls'] = [pt1[e]['image_versions2']['candidates'][0]['url'] for e in range(len(pt1))]
@novitae ?

2021-11-23 18:56 UTC, novitae commented on instagram_scraper/app.py
> +                        node['urls'] = [pt1[e]['image_versions2']['candidates'][0]['url'] for e in range(len(pt1))]
Sorry i deleted my work so i can't tell you more details. If you want i can send you the api response that causes the graphql error, so you can see by yourself why i am filling these dictionary paths

2021-12-01 19:34 UTC, AlexNik commented on instagram_scraper/app.py
> +                        node['urls'] = [pt1[e]['image_versions2']['candidates'][0]['url'] for e in range(len(pt1))]
@novitae Could you fix the code review and i'll merge it.
Change 611, 6112 lines to
```
node['urls'] = [carousel_media['image_versions2']['candidates'][0]['url'] for carousel_media in details['carousel_media'])]
```

2022-01-21 08:05 UTC, closed without merging